export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: 'superiores' | 'inferiores' | 'calcados' | 'cabeca';
  sizes: string[];
  image: string;
  featured?: boolean;
}

export const products: Product[] = [
  // Superiores (10 produtos)
  {
    id: 'sup-001',
    name: 'Top Esportivo Pérola',
    description: 'Top esportivo em tons perolados com suporte médio. Perfeito para treinos de alta intensidade.',
    price: 89.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
    featured: true,
  },
  {
    id: 'sup-002',
    name: 'Cropped de Compressão',
    description: 'Cropped com tecnologia de compressão para melhor desempenho e conforto.',
    price: 79.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'sup-003',
    name: 'Camiseta Dry Fit',
    description: 'Camiseta em tecido dry fit que absorve umidade. Ideal para academia.',
    price: 69.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'sup-004',
    name: 'Regata Cavada Gigi',
    description: 'Regata cavada com estilo casual e confortável para treinos leves.',
    price: 59.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'sup-005',
    name: 'Moletom Leve com Capuz',
    description: 'Moletom leve e respirável com capuz. Perfeito para pré e pós treino.',
    price: 129.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
    featured: true,
  },
  {
    id: 'sup-006',
    name: 'Top de Alça Larga',
    description: 'Top com alças largas para máximo conforto e suporte durante exercícios.',
    price: 85.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'sup-007',
    name: 'Blusa Manga Longa Respirável',
    description: 'Blusa de manga longa em tecido respirável. Ideal para treinos ao ar livre.',
    price: 99.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'sup-008',
    name: 'Body Esportivo Minimalista',
    description: 'Body esportivo com design minimalista e confortável para qualquer atividade.',
    price: 119.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
    featured: true,
  },
  {
    id: 'sup-009',
    name: 'Camiseta Gola Careca',
    description: 'Camiseta clássica com gola careca em tons neutros. Versátil e confortável.',
    price: 64.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'sup-010',
    name: 'Crop Top Mesh Transpassado',
    description: 'Crop top com detalhe mesh transpassado. Estilo casual e moderno.',
    price: 74.90,
    category: 'superiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },

  // Inferiores (8 produtos)
  {
    id: 'inf-001',
    name: 'Legging Alta Compressão',
    description: 'Legging com cintura alta e compressão. Suporte total para seus treinos.',
    price: 139.90,
    category: 'inferiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
    featured: true,
  },
  {
    id: 'inf-002',
    name: 'Shorts de Academia Pearl',
    description: 'Shorts em tons perolados com cintura elástica. Confortável e elegante.',
    price: 89.90,
    category: 'inferiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'inf-003',
    name: 'Calça Legging Cintura Alta',
    description: 'Legging com cintura alta que modela e oferece máximo conforto.',
    price: 149.90,
    category: 'inferiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
    featured: true,
  },
  {
    id: 'inf-004',
    name: 'Bermuda Tactel',
    description: 'Bermuda em tecido tactel respirável. Perfeita para treinos ao ar livre.',
    price: 79.90,
    category: 'inferiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'inf-005',
    name: 'Legging com Side Pocket',
    description: 'Legging com bolsos laterais para guardar seus pertences durante o treino.',
    price: 129.90,
    category: 'inferiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'inf-006',
    name: 'Shorts Ciclista Premium',
    description: 'Shorts ciclista com tecnologia premium. Conforto e estilo em um só lugar.',
    price: 69.90,
    category: 'inferiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'inf-007',
    name: 'Calça Jogger Moletom',
    description: 'Calça jogger em moletom leve. Perfeita para dias de descanso ativo.',
    price: 119.90,
    category: 'inferiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'inf-008',
    name: 'Legging Estampada Floral',
    description: 'Legging com estampa floral delicada. Estilo e conforto combinados.',
    price: 134.90,
    category: 'inferiores',
    sizes: ['P', 'M', 'G', 'GG'],
    image: '/images/product-placeholder.jpg',
  },

  // Calçados (7 produtos)
  {
    id: 'cal-001',
    name: 'Tênis Corrida Lite',
    description: 'Tênis leve para corrida. Tecnologia de amortecimento avançada.',
    price: 249.90,
    category: 'calcados',
    sizes: ['33', '34', '35', '36', '37', '38', '39', '40'],
    image: '/images/product-placeholder.jpg',
    featured: true,
  },
  {
    id: 'cal-002',
    name: 'Sneaker Casual Gigi\'s',
    description: 'Sneaker casual com design exclusivo Gigi\'s Wear. Versátil e confortável.',
    price: 199.90,
    category: 'calcados',
    sizes: ['33', '34', '35', '36', '37', '38', '39', '40'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'cal-003',
    name: 'Tênis Academia Flex',
    description: 'Tênis com tecnologia flex para máxima mobilidade em treinos.',
    price: 179.90,
    category: 'calcados',
    sizes: ['33', '34', '35', '36', '37', '38', '39', '40'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'cal-004',
    name: 'Slide Comfort Pérola',
    description: 'Slide confortável em tons perolados. Perfeito para pós treino.',
    price: 89.90,
    category: 'calcados',
    sizes: ['33', '34', '35', '36', '37', '38', '39', '40'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'cal-005',
    name: 'Tênis Caminhada Cloud',
    description: 'Tênis de caminhada com tecnologia cloud. Conforto o dia todo.',
    price: 219.90,
    category: 'calcados',
    sizes: ['33', '34', '35', '36', '37', '38', '39', '40'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'cal-006',
    name: 'Sneaker Minimalist White',
    description: 'Sneaker minimalista branca. Combina com tudo em seu guarda-roupa.',
    price: 189.90,
    category: 'calcados',
    sizes: ['33', '34', '35', '36', '37', '38', '39', '40'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'cal-007',
    name: 'Tênis Treino Multi',
    description: 'Tênis versátil para múltiplos tipos de treino. Suporte total.',
    price: 229.90,
    category: 'calcados',
    sizes: ['33', '34', '35', '36', '37', '38', '39', '40'],
    image: '/images/product-placeholder.jpg',
    featured: true,
  },

  // Cabeça (5 produtos)
  {
    id: 'cab-001',
    name: 'Boné Aba Curva Pérola',
    description: 'Boné com aba curva em tons perolados. Proteção e estilo.',
    price: 59.90,
    category: 'cabeca',
    sizes: ['Único'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'cab-002',
    name: 'Headband Esportivo',
    description: 'Headband esportivo que mantém o cabelo no lugar durante treinos.',
    price: 29.90,
    category: 'cabeca',
    sizes: ['Único'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'cab-003',
    name: 'Bucket Hat Gigi\'s',
    description: 'Bucket hat com logo Gigi\'s Wear. Estilo casual e confortável.',
    price: 79.90,
    category: 'cabeca',
    sizes: ['Único'],
    image: '/images/product-placeholder.jpg',
    featured: true,
  },
  {
    id: 'cab-004',
    name: 'Visor Esportivo',
    description: 'Visor esportivo para proteger do sol durante atividades ao ar livre.',
    price: 39.90,
    category: 'cabeca',
    sizes: ['Único'],
    image: '/images/product-placeholder.jpg',
  },
  {
    id: 'cab-005',
    name: 'Touca de Treino',
    description: 'Touca respirável para treinos intensos. Mantém você fresco e seco.',
    price: 44.90,
    category: 'cabeca',
    sizes: ['Único'],
    image: '/images/product-placeholder.jpg',
  },
];

export const categories = [
  { id: 'superiores', name: 'Superiores', description: 'Tops, camisetas e blusas' },
  { id: 'inferiores', name: 'Inferiores', description: 'Leggings, shorts e calças' },
  { id: 'calcados', name: 'Calçados', description: 'Tênis, sneakers e slides' },
  { id: 'cabeca', name: 'Cabeça', description: 'Bonés, headbands e visores' },
];
